name: Notify Telegram on Push
on:
  push:
    branches:
      - '**'  # Monitor all branches

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensure full commit history is fetched

    - name: Send notification to Telegram Group
      env:
        TELEGRAM_TOKEN: 6440588108:AAEDYXXQL7L1jYGnxtChytq4dfajZQOqVGA
        TELEGRAM_GROUP_CHAT_ID: -1002261193147
      run: |
        # Check if this is a new branch
        if [ "${{ github.event.created }}" = "true" ]; then
          # This is a new branch
          branch_name="${{ github.ref_name }}"
          user_name="${{ github.actor }}"
          message="🌿 New branch created: *$branch_name* by *$user_name*"
        else
          # This is a push to an existing branch
          branch_name="${{ github.ref_name }}"
          user_name="${{ github.actor }}"
          commit_count=$(git rev-list --count ${{ github.event.before }}..${{ github.sha }})
          message="🚀 Push to branch *$branch_name* by *$user_name*
        Number of commits: $commit_count"
        fi

        # Send the message to the group chat
        curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
          -d chat_id="${TELEGRAM_GROUP_CHAT_ID}" \
          -d text="$message" \
          -d parse_mode="Markdown"
