name: Notify Telegram on Push

on:
  push:
    branches:
      - main  # Change this to the branch you want to monitor

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Send notification to Telegram
      env:
        TELEGRAM_TOKEN: 6440588108:AAEDYXXQL7L1jYGnxtChytq4dfajZQOqVGA
        TELEGRAM_CHAT_IDS: 579397885  # Store multiple chat IDs here, comma-separated
      run: |
        message="🚀 New push on repository *${{ github.repository }}* by *${{ github.actor }}* on branch *${{ github.ref }}*\n\nCommit Message: `$(git log -1 --pretty=%B)`"

        # Convert TELEGRAM_CHAT_IDS into an array by splitting the string by comma
        IFS=',' read -r -a chat_ids <<< "$TELEGRAM_CHAT_IDS"
        
        # Loop through each chat ID and send the message
        for chat_id in "${chat_ids[@]}"
        do
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
          -d chat_id="$chat_id" \
          -d text="$message" \
          -d parse_mode="Markdown"
        done
