name: Notify Telegram on Push

on:
  push:
    branches:
      - '**'

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Send notification to Telegram Group
      env:
        TELEGRAM_TOKEN: 6440588108:AAEDYXXQL7L1jYGnxtChytq4dfajZQOqVGA
        TELEGRAM_GROUP_CHAT_ID: -1002261193147
      run: |
        # Get the list of commits in the current push
        commits=$(git log ${{ github.event.before }}..${{ github.sha }} --pretty=format:"%h %s by %an")

        # Loop through each commit and send a separate message
        while IFS= read -r commit; do
          message="🚀 New commit pushed by *${{ github.actor }}* on branch *${{ github.ref }}*   ➡️Commit: $commit"

          # Send the message for each commit
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_GROUP_CHAT_ID}" \
            -d text="$message" \
            -d parse_mode="Markdown"

          # Sleep for a second between messages to avoid rate limits
          sleep 1
        done <<< "$commits"
