name: Notify Telegram on Push

on:
  push:
    branches:
      - '**'  # Monitor all branches

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensure full commit history is fetched

    - name: Send notification to Telegram Group
      env:
        TELEGRAM_TOKEN: 6440588108:AAEDYXXQL7L1jYGnxtChytq4dfajZQOqVGA
        TELEGRAM_GROUP_CHAT_ID: -1002261193147
      run: |
        # Fallback to the first commit if this is the first push or no valid range is found
        if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
          echo "First push or no previous commit found, getting the full commit history."
          commit_range=$(git rev-list --max-parents=0 HEAD)..${{ github.sha }}
        else
          commit_range=${{ github.event.before }}..${{ github.sha }}
        fi

        # Check if the commit range is valid
        if git rev-list $commit_range >/dev/null 2>&1; then
          echo "Commit range is valid: $commit_range"
        else
          echo "Invalid commit range. Using last commit only."
          commit_range=${{ github.sha }}^..${{ github.sha }}
        fi

        # Get the list of commits pushed in the current push
        commit_messages=$(git log $commit_range --pretty=format:"➡️ %s by %an")

        # Construct the message with all commit messages
        message="🚀 New push by *${{ github.actor }}* on branch *${{ github.ref }}*       Commits: $commit_messages"

        # Send the message to the group chat
        curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
          -d chat_id="${TELEGRAM_GROUP_CHAT_ID}" \
          -d text="$message" \
          -d parse_mode="Markdown"
