name: Notify Telegram on Push

on:
  push:
    branches:
      - '**'  # Monitor all branches
    tags:
      - '**'  # Monitor all tags

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Send notification to Telegram Group
      env:
        TELEGRAM_TOKEN: 6440588108:AAEDYXXQL7L1jYGnxtChytq4dfajZQOqVGA
        TELEGRAM_GROUP_CHAT_ID: -1002261193147
      run: |
        # Get the latest commit message
        commit_message=$(git log -1 --pretty=%B)

        # Construct the message for Telegram
        message="🚀 New push on repository *${{ github.repository }}* by *${{ github.actor }}* on branch *${{ github.ref }}*\n\nCommit Message: \"$commit_message\""

        # Send the message to the group chat
        curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
          -d chat_id="${TELEGRAM_GROUP_CHAT_ID}" \
          -d text="$message" \
          -d parse_mode="Markdown"

        # Sleep for 1 second to avoid rate-limiting
        sleep 1
